#pragma config(Motor,  motorB,          left,          tmotorNXT, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          right,         tmotorNXT, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
motor[motorB] = 100;
motor[motorC] = 100;



wait1Msec(11111111);
}
